manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/lynnlee0522 # 修改这里
  - name: nxtkb
    url-base: https://github.com/nxtkb
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: ink_rotation # 修改这里，指定分支名
    import: app/west.yml
  - name: zmk-behavior-report
    remote: nxtkb
    revision: main
    import: west.yml
  - name: cirque-input-module
    remote: nxtkb
    revision: main
  self:
    path: config
